<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>scala</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~C</string>
	<key>name</key>
	<string>Chisel</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>===</string>
			<key>name</key>
			<string>keyword.operator.comparison.chisel</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#basic-data-types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#state-elements</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#support-type-built-ins-scala</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\w)(when|\.elsewhen|\.otherwise|unless|switch|is)\b</string>
			<key>name</key>
			<string>keyword.control.chisel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(:=|&lt;&gt;)</string>
			<key>name</key>
			<string>keyword.operator.assignment.chisel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(INPUT|OUTPUT)\b</string>
			<key>name</key>
			<string>constant.language.chisel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Cat|log2Up|log2Ceil|log2Down|log2Floor|isPow2|foldR|PopCount|Reverse|UIntToOH|Mux1H|FillInterleaved|andR|orR|xorR)\b</string>
			<key>name</key>
			<string>support.function.chisel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(fill|forall|exists|contains|count|indexWhere|lastIndexWhere|onlyIndexWhere)\b</string>
			<key>name</key>
			<string>support.function.vec.chisel</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Bundle|Module|Tester)\b</string>
			<key>name</key>
			<string>support.class.chisel</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.scala</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>basic-data-types</key>
		<dict>
			<key>match</key>
			<string>\b(UInt|Bool|SInt|Bits|Data|Clock|Complex)\b</string>
			<key>name</key>
			<string>storage.type.basic.chisel</string>
		</dict>
		<key>state-elements</key>
		<dict>
			<key>match</key>
			<string>\b(Reg|Mem|Vec)\b</string>
			<key>name</key>
			<string>storage.type.state.chisel</string>
		</dict>
		<key>support-type-built-ins-scala</key>
		<dict>
			<key>match</key>
			<string>\b(Enum|RegInit|RegNext|RegReset|RegEnable|ShiftRegister|LFSR16|ValidIO|Valid|DecoupledIO|Decoupled|EnqIO|DeqIO|DecoupledIOC|ArbiterIO|ArbiterCtrl|LockingArbiterLike|LockingRRArbiter|LockingArbiter|RRArbiter|Arbiter|Counter|QueueIO|Queue|AsyncFifo|Pipe|PriorityMux|PriorityEncoderOH|MemRead|MemSeqRead|MemReadWrite|MemWrite)\b</string>
			<key>name</key>
			<string>support.type.built-ins.scala</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.chisel</string>
	<key>uuid</key>
	<string>C3138EC3-B914-4E0E-A4B3-DD2EC168440E</string>
</dict>
</plist>
